@echo off
setlocal enabledelayedexpansion

if "%~1"=="" (
    echo.
    echo  Drag a .svlib file onto this script to import it into sv_lib.json.
    echo  The .svlib file is generated by the Sovereign Alphabet Editor.
    pause & exit /b
)

set "svlib=%~1"
:: Resolve project root: this script lives in legacy\scripts\, so walk up
:: two levels and let the for-loop normalize to an absolute path.
for %%A in ("%~dp0..\..") do set "root=%%~fA\"
set "libfile=!root!sv_lib.json"

echo.
echo  Importing: %~nx1
echo  Into:      !libfile!
echo.

powershell -NoProfile -ExecutionPolicy Bypass -Command ^
    "$import = Get-Content '%svlib%' -Raw | ConvertFrom-Json;" ^
    "$entry  = $import.entry;" ^
    "if (-not $entry) { Write-Host '[ERROR] Invalid .svlib file.'; exit 1 };" ^
    "if (-not (Test-Path '%libfile%')) { $lib = [pscustomobject]@{version=1;alphabets=@()} } else { $lib = Get-Content '%libfile%' -Raw | ConvertFrom-Json };" ^
    "$existing = $lib.alphabets | Where-Object { $_.id -eq $entry.id };" ^
    "if ($existing) { Write-Host '[ERROR] Alphabet ID '''+$entry.id+''' already exists in library. Choose a different name in the editor.'; exit 1 };" ^
    "$lib.alphabets += $entry;" ^
    "$lib | ConvertTo-Json -Depth 5 | Set-Content '%libfile%' -Encoding UTF8;" ^
    "Write-Host '[OK] Imported: '+$entry.name+' ('+$entry.base+' chars, fp:'+$entry.fingerprint+')';"

if errorlevel 1 ( pause & exit /b )
echo.
echo  The alphabet is now available in Sovereign_Encode.bat and Sovereign_Decode.bat.
pause
