"""
sv_kvcrypto.py - Key Vault encryption layer

AES-256-CBC with explicit salt/IV generated by Python and stored separately
in the key record. The encoded output has zero crypto overhead — no Salted__
prefix, no salt bytes embedded in the file. All decryption parameters live in
the key record.

Dependencies: Python stdlib only (secrets, hashlib, subprocess) + OpenSSL on PATH.

Manual recovery path (no app required):
  1. Read salt_hex and iv_hex from the printed key record
  2. Derive key: PBKDF2-HMAC-SHA256(password.utf8, bytes.fromhex(salt_hex), 100000, 32)
  3. Run:
       openssl aes-256-cbc -d -nosalt -K <key_hex> -iv <iv_hex> \\
           -in encrypted.bin -out recovered_file
"""

from __future__ import annotations

import hashlib
import os
import secrets
import subprocess


class KvCryptoError(Exception):
    """Raised when KV crypto fails. Message is user-facing."""
    pass


# PBKDF2 / AES constants
_KDF_ALGORITHM  = 'sha256'
_KDF_ITERATIONS = 100_000
_KEY_BYTES      = 32   # AES-256
_SALT_BYTES     = 16
_IV_BYTES       = 16


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _derive_key(password: str, salt: bytes) -> bytes:
    """PBKDF2-HMAC-SHA256: password + salt → 32-byte AES key."""
    return hashlib.pbkdf2_hmac(
        _KDF_ALGORITHM,
        password.encode('utf-8'),
        salt,
        _KDF_ITERATIONS,
        _KEY_BYTES,
    )


def _openssl_exe(openssl_path: str) -> str:
    """Return the OpenSSL executable path (user setting or 'openssl' on PATH)."""
    return openssl_path.strip() if openssl_path.strip() else 'openssl'


def _run_openssl(args: list[str], openssl_path: str = '') -> tuple[int, str]:
    """Run openssl with the given argument list. Returns (exit_code, combined_output)."""
    cmd = [_openssl_exe(openssl_path)] + args
    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            encoding='utf-8',
            errors='replace',
            timeout=60,
            creationflags=0x08000000 if os.name == 'nt' else 0,
        )
        output = (proc.stdout or '') + (proc.stderr or '')
        return proc.returncode, output
    except FileNotFoundError:
        raise KvCryptoError(
            'openssl not found. Install OpenSSL and add it to PATH, '
            'or set the path in Settings.'
        )
    except subprocess.TimeoutExpired:
        raise KvCryptoError('OpenSSL timed out during KV encrypt/decrypt.')


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def kv_encrypt(
    in_path: str,
    out_path: str,
    password: str,
    openssl_path: str = '',
) -> tuple[str, str]:
    """
    Encrypt *in_path* → *out_path* with AES-256-CBC.

    A fresh random salt and IV are generated each call.  The **Salted__**
    prefix is deliberately *not* written to the output — the ciphertext is
    raw bytes.  The caller must store the returned (salt_hex, iv_hex) in the
    key record; without them the data cannot be decrypted.

    Returns (salt_hex, iv_hex).  Raises KvCryptoError on failure.
    """
    if not password:
        raise KvCryptoError('Password cannot be empty for KV encryption.')

    salt = secrets.token_bytes(_SALT_BYTES)
    iv   = secrets.token_bytes(_IV_BYTES)
    key  = _derive_key(password, salt)

    code, out = _run_openssl(
        [
            'aes-256-cbc',
            '-nosalt',
            '-K', key.hex(),
            '-iv', iv.hex(),
            '-in', str(in_path),
            '-out', str(out_path),
        ],
        openssl_path,
    )
    if code != 0:
        raise KvCryptoError(f'OpenSSL encrypt failed: {out.strip() or "unknown error"}')

    return salt.hex(), iv.hex()


def kv_decrypt(
    in_path: str,
    out_path: str,
    password: str,
    salt_hex: str,
    iv_hex: str,
    openssl_path: str = '',
) -> None:
    """
    Decrypt *in_path* → *out_path* using stored salt_hex / iv_hex.

    Raises KvCryptoError on failure (wrong password, bad key record, etc.).
    """
    if not password:
        raise KvCryptoError('Password cannot be empty for KV decryption.')

    try:
        salt = bytes.fromhex(salt_hex)
    except ValueError:
        raise KvCryptoError(f'Invalid salt_hex in key record: {salt_hex!r}')
    try:
        bytes.fromhex(iv_hex)  # validate
    except ValueError:
        raise KvCryptoError(f'Invalid iv_hex in key record: {iv_hex!r}')

    key = _derive_key(password, salt)

    code, out = _run_openssl(
        [
            'aes-256-cbc', '-d',
            '-nosalt',
            '-K', key.hex(),
            '-iv', iv_hex,
            '-in', str(in_path),
            '-out', str(out_path),
        ],
        openssl_path,
    )
    if code != 0:
        raise KvCryptoError(
            f'OpenSSL decrypt failed (wrong password or corrupted data?): '
            f'{out.strip() or "unknown error"}'
        )


def kdf_params() -> dict:
    """Return the KDF parameters stored in every key record."""
    return {
        'kdf': f'pbkdf2-{_KDF_ALGORITHM}',
        'kdf_iterations': _KDF_ITERATIONS,
    }


# ---------------------------------------------------------------------------
# HTML helpers (no external deps)
# ---------------------------------------------------------------------------

def _html_escape(s: str) -> str:
    return str(s).replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;').replace('"', '&quot;')


def _js_escape(s: str) -> str:
    return str(s).replace('\\', '\\\\').replace("'", "\\'")


# ---------------------------------------------------------------------------
# Recovery HTML — named sections (edit each independently)
# ---------------------------------------------------------------------------

# To restyle the recovery page: edit _RECOVERY_CSS only.
_RECOVERY_CSS = """\
  body{font-family:system-ui,sans-serif;max-width:740px;margin:40px auto;padding:0 20px;background:#0f172a;color:#f1f5f9}
  h1{color:#3b82f6;margin-bottom:6px}
  h2{font-size:15px;font-weight:600;margin-bottom:10px}
  p{color:#94a3b8;font-size:13px;margin-bottom:10px}
  .card{background:#1e293b;border:1px solid #334155;border-radius:8px;padding:20px;margin:16px 0}
  label{display:block;margin-bottom:5px;font-size:11px;color:#94a3b8;text-transform:uppercase;font-weight:600;letter-spacing:.06em}
  input[type=password]{width:100%;padding:10px 12px;background:#0f172a;border:1px solid #334155;border-radius:6px;color:#f1f5f9;font-size:14px;box-sizing:border-box;margin-bottom:10px}
  button{padding:10px 20px;background:#3b82f6;color:#fff;border:none;border-radius:6px;cursor:pointer;font-size:14px;font-weight:600}
  button:hover{background:#2563eb}
  pre{background:#0f172a;border:1px solid #334155;border-radius:6px;padding:12px;font-size:12px;white-space:pre-wrap;word-break:break-all;color:#4ade80;margin-top:8px}
  .kv{display:grid;grid-template-columns:160px 1fr;gap:8px;padding:6px 0;border-bottom:1px solid #334155;font-size:13px}
  .kv:last-child{border-bottom:none}
  .kl{color:#94a3b8}
  .kv pre{margin:0;border:none;padding:0;background:none;color:#f1f5f9;font-size:12px}
  .warn{background:#7c2d12;border:1px solid #dc2626;padding:12px;border-radius:6px;margin:16px 0;font-size:13px}
  .hidden{display:none}
  code{background:#0f172a;border-radius:3px;padding:1px 5px;font-size:12px}"""


def _recovery_meta_rows(record: dict, salt_hex: str, iv_hex: str, iterations: int) -> str:
    """Build the .kv grid rows that display the record's crypto parameters.

    Add new fields here when the key-record schema grows — no other section
    of the recovery page needs to change.
    """
    def row(label: str, value: str, mono: bool = False) -> str:
        inner = f'<pre>{_html_escape(value)}</pre>' if mono else f'<span>{_html_escape(value)}</span>'
        return f'  <div class="kv"><span class="kl">{label}</span>{inner}</div>\n'

    rows  = row('Record label',  record.get('label', 'Key Vault Record'))
    rows += row('Record ID',     record.get('id', ''))
    rows += row('Created',       record.get('created', ''))
    rows += row('Alphabet',      record.get('alphabet_name', ''))
    rows += row('Encoded chars', str(record.get('char_count', '')))
    rows += row('KDF',           f'PBKDF2-HMAC-SHA256, {iterations} iterations')
    rows += row('Salt (hex)',    salt_hex, mono=True)
    rows += row('IV (hex)',      iv_hex,   mono=True)
    return rows


def _recovery_script_block(salt_hex: str, iv_hex: str, iterations: int) -> str:
    """Return the <script> block for in-browser PBKDF2 key derivation.

    This is the only place to update if the KDF algorithm or OpenSSL
    command syntax ever changes.
    """
    return f"""<script>
const SALT_HEX = '{_js_escape(salt_hex)}';
const IV_HEX   = '{_js_escape(iv_hex)}';
const ITER     = {iterations};

async function deriveKey() {{
  const pw = document.getElementById('pw').value;
  if (!pw) {{ alert('Please enter your password.'); return; }}
  try {{
    const enc  = new TextEncoder();
    const km   = await crypto.subtle.importKey('raw', enc.encode(pw), 'PBKDF2', false, ['deriveBits']);
    const salt = hexBytes(SALT_HEX);
    const bits = await crypto.subtle.deriveBits(
      {{name:'PBKDF2', salt, iterations:ITER, hash:'SHA-256'}}, km, 256
    );
    const keyHex = toHex(new Uint8Array(bits));
    document.getElementById('key-hex').textContent = keyHex;
    document.getElementById('key-result').classList.remove('hidden');
    document.getElementById('openssl-cmd').textContent =
      'openssl aes-256-cbc -d -nosalt \\\\\\n' +
      '    -K ' + keyHex + ' \\\\\\n' +
      '    -iv ' + IV_HEX + ' \\\\\\n' +
      '    -in encrypted.bin -out recovered_original';
    document.getElementById('step2').classList.remove('hidden');
    document.getElementById('step3').classList.remove('hidden');
  }} catch(e) {{
    alert('Error: ' + e.message);
  }}
}}
function hexBytes(h) {{
  const a = new Uint8Array(h.length >> 1);
  for (let i = 0; i < a.length; i++) a[i] = parseInt(h.slice(i*2, i*2+2), 16);
  return a;
}}
function toHex(b) {{
  return Array.from(b).map(x => x.toString(16).padStart(2,'0')).join('');
}}
</script>"""


def build_recovery_html(record: dict) -> str:
    """
    Generate a standalone offline recovery.html for *record*.

    The HTML uses the browser's native Web Crypto API (PBKDF2) to derive the
    AES key and display the exact OpenSSL command.  No Python, no app,
    no internet required — just a browser and OpenSSL.

    To change styling: edit ``_RECOVERY_CSS``.
    To add metadata fields: edit ``_recovery_meta_rows``.
    To update the KDF/OpenSSL command: edit ``_recovery_script_block``.
    """
    salt_hex   = record.get('salt_hex', '')
    iv_hex     = record.get('iv_hex', '')
    label      = record.get('label', 'Key Vault Record')
    iterations = record.get('kdf_iterations', _KDF_ITERATIONS)

    original_text  = record.get('original_text', '')
    original_block = (
        f'\n<div class="card">\n  <h2>Stored original text</h2>\n'
        f'  <pre id="original-text">{_html_escape(original_text)}</pre>\n</div>'
        if original_text else ''
    )

    meta_rows = _recovery_meta_rows(record, salt_hex, iv_hex, iterations)
    script    = _recovery_script_block(salt_hex, iv_hex, iterations)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Sovereign Recovery — {_html_escape(label)}</title>
<style>
{_RECOVERY_CSS}
</style>
</head>
<body>
<h1>Sovereign Tattoo — Recovery</h1>
<p>Offline, self-contained recovery page. No internet or app required — just a browser and OpenSSL.</p>

<div class="card">
{meta_rows}</div>
{original_block}
<div class="card">
  <h2>Step 1 — Derive AES key from your password</h2>
  <p>Enter the password you chose when encoding. The key is derived in-browser using Web Crypto API — your password never leaves this page.</p>
  <label for="pw">Password</label>
  <input type="password" id="pw" placeholder="Enter your encoding password" autocomplete="off">
  <button onclick="deriveKey()">Derive key</button>
  <div id="key-result" class="hidden" style="margin-top:14px">
    <label>Derived AES-256 key (hex)</label>
    <pre id="key-hex"></pre>
  </div>
</div>

<div class="card hidden" id="step2">
  <h2>Step 2 — Decode the tattoo string to encrypted bytes</h2>
  <p>
    The tattoo string is base-encoded ciphertext. Decode it using the Sovereign app (Decode tab),
    or manually using the alphabet characters from the key record printout.
    Save the decoded binary as <code>encrypted.bin</code>.
  </p>
</div>

<div class="card hidden" id="step3">
  <h2>Step 3 — Decrypt with OpenSSL</h2>
  <p>Run this command in a terminal (OpenSSL must be installed):</p>
  <pre id="openssl-cmd"></pre>
</div>

<div class="warn">
  &#9888; This file contains cryptographic parameters. Keep it with your key record backup,
  stored separately from the encoded tattoo string.
</div>

{script}
</body>
</html>"""
